name: General Report - Burn Up and Down Charts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub matplotlib numpy
      - name: Generate Burn Down Chart
        run: python Ichicawa_tools_generators/burn_down_chart.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Upload Burn Down Chart
        uses: actions/upload-artifact@v2
        with:
          name: burn_down_chart
          path: burn_down_chart.png
      - name: Generate Burn Up Chart
        run: python Ichicawa_tools_generators/burn_up_chart.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Upload Burn Up Chart
        uses: actions/upload-artifact@v2
        with:
          name: burn_up_chart
          path: burn_up_chart.png
